# Generated by Django 4.1 on 2022-09-03 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vechiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=255)),
                ('vehicle_cc', models.CharField(max_length=255)),
                ('vehicle_img', models.ImageField(upload_to='vechiles')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.classofvechiles')),
            ],
        ),
    ]
