# Generated by Django 4.1 on 2022-09-04 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_vechiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vechiles',
            old_name='vehicle_name',
            new_name='vehicle_type',
        ),
    ]
