# Generated by Django 4.1 on 2022-09-14 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vechiles',
            old_name='vehicle_type',
            new_name='vehicle_name',
        ),
    ]
